### ISSUE TITLE
Mix up with the use of customer_id and _customer_number in Customer class

### ISSUE THREAD

**Issue by bluman1** [ElarianLtd/python-sdk#7]
Hi,

The class variable customer_id and customer_number were initiated as _customer_id and _customer_number but the rest of the code used the variables without the leading underscore.
This makes it impossible to create a new Customer object and throws a RuntimeError("Either id or number is required").

I have added comments in the snippet below to see what I mean.

    
    _customer_id: str = None # code with issue
    _customer_number: dict = None # code with issue
    _identity_state: dict = None
    _messaging_state: dict = None
    _payment_state: dict = None
    _activity_state: dict = None
    _client = None

    def __init__(self, client, id=None, number=None, provider=None):
        self._client = client
        if id is not None:
            self._customer_id = id
        if number is not None:
            provider = (
                provider if provider is not None else 'CELLULAR'
            )
            self._customer_number = {"number": number, "provider": provider}

        if self.customer_id is None and self.customer_number is None:  # impact of issue felt here
            raise RuntimeError("Either id or number is required")`

**Comment by aksalj** [comment]
Hey @bluman1, thanks for this catch.

@nicholas-ngatia This breaking change was introduced with this [commit](https://github.com/ElarianLtd/python-sdk/commit/4a279b3a7ce13b3b4acd1a7c4423ea97e923126f)...
